### ISSUE TITLE
Example does not work with version of playwright >= 1.43.0

### ISSUE THREAD

**Issue by KSchrage-SIT** [cenfun/playwright-ct-vue#2]
Hello!

At least this commit (https://github.com/microsoft/playwright/commit/88e80cf948f76e1ad9a1fac2cfc3872232641c19) of playwright breaks the code of this repository. Starting with playwright 1.43.0 the commit is included. 

Since we are required to start / stop the coverage recording in chromium via beforeAll / afterAll we cannot make the coverage reporting work as explained here.

This is the error that comes up:
```
Error: "context" and "page" fixtures are not supported in "beforeAll" since they are created on a per-test basis.
If you would like to reuse a single page between tests, create context manually with browser.newContext(). See https://aka.ms/playwright/reuse-page for details.
If you would like to configure your page before each test, do that in beforeEach hook instead.
```

Is there any other way to access the - shared - page object globally?

Regards
Klemens

**Comment by cenfun** [comment]
Just update playwright to `1.46.0`, it seems works well.
see commit: https://github.com/cenfun/playwright-ct-vue/commit/b84ab08296284d9d1ce7ada51be1fc07cf9130a8

**Comment by KSchrage-SIT** [comment]
Thanks for your quick response. Did you also try a coverage report as described in the README? If so, could you commit the corresponding test-case to this repo so I can search for differences?

**Comment by cenfun** [comment]
Yes, here is my steps:
1, git clone https://github.com/cenfun/playwright-ct-vue.git
2, npm i
3, npm run test

test cases: https://github.com/cenfun/playwright-ct-vue/tree/main/tests

**Comment by KSchrage-SIT** [comment]
Allright I managed to get it running. It works with the auto-fixtures but fails with the beforeAll/afterAll approach. Maybe the README should be updated in this regard?

For anyone who struggles to get it working in a Typescript setup, here's my fixtures.ts for reference (sorry for the file-ending, but TS is not allowed):
[fixtures.txt](https://github.com/user-attachments/files/16611152/fixtures.txt)

**Comment by cenfun** [comment]
Thanks, The README is updated.
